[package]
name = "tilewater"
version = "0.1.0"
authors = ["Michael Mokrysz <hi@46b.it>"]

[dependencies]
clap = "2.23.1"
rand = "0.3"
piston_window = "0.61.0"
uuid = "0.4"

[[bin]]
name = "tilewater"
doc = false
